//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEntityApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employee_id { get; set; }
        public string employee_name { get; set; }
        public string department { get; set; }
        public Nullable<System.DateTime> joining_date { get; set; }
        public Nullable<int> mobile_no { get; set; }
    }
}
